# This is a basic workflow to help you get started with Actions

name: GithubWiki

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  githubWiki:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: |
          git remote add wikiwiki https://github.com/nahum-mendoza/wiki.wiki.git
          git config user.name github-actions
          git config user.email github-actions@github.com
          git subtree pull --prefix docs wiki master --squash --message="Merge wiki updates into docs."
          git subtree push --prefix docs wikiwiki master
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: echo Finish
